# Generated by Django 5.0.1 on 2024-02-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_education_alter_experience_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('start_date',), 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
    ]
